name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  #push:
  #  branches: ["**"]
  #  paths:
  #    - "dist/**"
  #    - "src/**"
  #    - "package*.json"
  #    - "requirements*.txt"
  #    - ".github/workflows/test.yaml"
  #    - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Test App"
        id: test
        run: |
          echo It Works!
